package com.example.tender;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;

import android.content.Intent;
import android.os.Bundle;
import android.service.autofill.FieldClassification;
import android.view.MotionEvent;
import android.view.View;
import android.widget.ImageButton;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class MainActivity extends AppCompatActivity {

    private static final Integer LOAD_SIZE = 15;
    double x1, y1, x2, y2;
    DishManager dishManager;
    RestaurantManager restaurantManager;
    List<Dish> generalDishes;
    List<Dish> likedDishes;
    List<Dish> dislikedDishes;

    Dish currentDish;

    FragmentManager fragmentManager;
    Fragment foodProfileFragment;
    Fragment currentFragment;

    ImageButton homeButton;
    ImageButton matchButton;

    Random rand;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        foodProfileFragment = new FoodProfileFragment();

        fragmentManager = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
        fragmentTransaction.add(R.id.fragment_container, foodProfileFragment);
        fragmentTransaction.commit();
        currentFragment = foodProfileFragment;

        homeButton = findViewById(R.id.homebutton);
        matchButton = findViewById(R.id.matchbutton);

        dishManager = new DishManager();
        restaurantManager = new RestaurantManager();
        generalDishes = new ArrayList<>();
        likedDishes = new ArrayList<>();
        dislikedDishes = new ArrayList<>();

        rand = new Random();

        dishManager.getDishes((l)->{ // l is the dishList generated by get single random dish

            generalDishes = l;
            //TODO: customize generalDishes according to user settings
            Collections.shuffle(generalDishes);

            if (generalDishes.size() == LOAD_SIZE && currentDish == null){
//                if (generalDishes.get(0).getBytes().length > 1) {
                    updateCurrentDish();
//                    if (currentDish.getBytes().length > 1)
                System.out.println(currentDish.getBytes().length);
                    passCurrentDishProfile(foodProfileFragment);
//                }
            }
            return null;
        });
    }

//    LongTermRelationship(){
//        for (Dish i:generalDishes){
//           if  i.getRestaurant().getDineIn().equals("no") {
//                generalDishes.remove(i);
//            }
//        }
//    }

//    public void editDietaryRestrictions(){
//        for (Dish dish:generalDishes){
//            if (user.getGF = "y"){
//                deleteGluten(dish);
//            }
//            if (user.getDF = "y"){
//                onDietaryFree(dish);
//            }
//            if
//                deleteNonVegetarian             );
//        }
//    }

    public void retrieveUserInfo(){

    }

    //TODO: Implement this method and all the other dietary restrictions
    public void deleteGluten(Dish dish){
        if (dish.getGlutenFree().equals("n")){
            generalDishes.remove(dish);
        }
    }

    public void deleteDairy(Dish dish){
        if (dish.getDairyFree().equals("n")){
            generalDishes.remove(dish);
        }
    }

    public void deleteNonVegetarian(Dish dish){
        if (dish.getVegetarian().equals("n")){
            generalDishes.remove(dish);
        }
    }

    public void deleteNonVegan(Dish dish){
        if (dish.getVegan().equals("n")){
            generalDishes.remove(dish);
        }
    }

    @Override
    public boolean onTouchEvent(MotionEvent touchEvent) {
        if (currentDish != null) {
            switch (touchEvent.getAction()) {
                case MotionEvent.ACTION_DOWN:
                    x1 = touchEvent.getX();
                    y1 = touchEvent.getY();
                    break;
                case MotionEvent.ACTION_UP:
                    x2 = touchEvent.getX();
                    y2 = touchEvent.getY();
                    if (Math.abs(x1 - x2) > 30) {
                        if (x1 > x2) { // swiping left
                            onSwipeLeft();
                        } else if (x1 < x2) { // swiping right
                            onSwipeRight();
                        }
                    }
                    break;
            }
        }
        return false;
    }

    public void passCurrentDishProfile(Fragment fragment){
        System.out.println("------------------------------sending currentDish" +
                (currentDish.getBytes().length));
        Bundle bundle = new Bundle();
        bundle.putParcelable("currentDish", currentDish);
        fragment.setArguments(bundle);
    }

    public void updateCurrentDish(){
        int randomNum = rand.nextInt(generalDishes.size());
        while (dislikedDishes.contains(generalDishes.get(randomNum))) {
            randomNum = rand.nextInt(generalDishes.size());
        }
        currentDish = generalDishes.get(randomNum);
    }

    public void onSwipeRight(){
        likedDishes.add(currentDish);
        updateCurrentDish();
        Intent i = new Intent(MainActivity.this, MatchDisplay.class);
//        i.putExtra("matchedList", likedDishes);
        startActivity(i);
    }

    public void onSwipeLeft(){
        dislikedDishes.add(currentDish);
        updateCurrentDish();
        passCurrentDishProfile(foodProfileFragment);
    }

    @Override
    protected void onPause() {
        super.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
    }
}